# Veri Analizi - Part 1: Numpy

# 5. Numpy

## 5.1 Import Numpy

In [1]:
import numpy as np

## 5.2 Arrayler

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Aralık Oluşturmak

In [4]:
d = np.arange(10, 25, 5)
d

array([10, 15, 20])

In [5]:
e = np.linspace(0, 2, 9)
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
f = np.random.random((2, 2)) * 10
f

array([[2.10531209, 7.8939707 ],
       [2.34471696, 5.05345985]])

## 5.3 Matematik Operatörleri

In [7]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

### Çarpım

In [8]:
np.multiply(a, b)

array([10, 40, 90])

### Kare Alma

In [9]:
np.sqrt(100)

10.0

### Logaritma

In [10]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738])

## 5.4 Trigonometri

In [11]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162])

In [12]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 ])

## 5.5 Özetler

In [13]:
a = np.array([10, 20, 30, 40, 50, 60])
b = np.array([1, 2, 3, 4, 5, 6])

### Toplam

In [14]:
a.sum() 

210

### Minimum

In [15]:
a.min()

10

### Maksimum

In [16]:
b.max()

6

### Kümülatif Toplam

In [17]:
b.cumsum() 

array([ 1,  3,  6, 10, 15, 21])

### Ortalama

In [18]:
a.mean() 

35.0

### Standard Sapma

In [19]:
np.std(b)

1.707825127659933